### ISSUE TITLE
there is no n_gpus!

### ISSUE THREAD

**Issue by Xjmengnieer** [uzh-dqbm-cmi/ARGON#10]
Is there any error in the code here！！As shown in the figure：

**Comment by Xjmengnieer** [comment]
Is there any error in the code here！！As shown in the figure：
![image](https://user-images.githubusercontent.com/88227513/204293109-22acdb12-8028-43c1-9dcf-063508e8910e.png)

This problem occurs in file m2trGen,py on line 104

**Comment by nooralahzadeh** [comment]
Hi, Here you have the `n_gpu` as parameter!  It should be n_gpu! Thanks for reporting the issue!
https://github.com/uzh-dqbm-cmi/ARGON/blob/416c5f39370ffb0c52081b185b3af42af9e22a09/src/main_progressive.py#L85
