### ISSUE TITLE
How to get the MIRQI tools

### ISSUE THREAD

**Issue by Xjmengnieer** [uzh-dqbm-cmi/ARGON#11]
Hi author, I want to reproduce your paper on my own dataset, I saw that you used MIRQI tool in the data preprocessing, but I looked at its paper and found that it does not have open source code, Could you tell me how to use this MIRQI  tool?

**Comment by nooralahzadeh** [comment]
Hi,
It is mentioned on page 3 `To do so, we employed MIRQI tools implemented by Zhang et al. (2020).`  You should look at `https://ojs.aaai.org/index.php/AAAI/article/view/6989` and find the implementation!

**Comment by Xjmengnieer** [comment]
I did check the link you gave, and as you can see below, there doesn't seem to be any actual information available other than the paper PDF file！！！
![image](https://user-images.githubusercontent.com/88227513/205495803-7d5210b8-bac0-41cd-adbc-106b9bab1730.png)

**Comment by nooralahzadeh** [comment]
You can find information about MIRQI inside the paper. You can either contact the authors or give me your email address and If i found their implementation that was shared with me, i will send to you.

**Comment by Xjmengnieer** [comment]
ok, thanks!!!!!

**Comment by Xjmengnieer** [comment]
ok, thanks!!!
my email " xianjm21@mails.tsinghua.edu.cn "

**Comment by nooralahzadeh** [comment]
Done

**Comment by nooralahzadeh** [comment]
You can also find the MIRQI code base here `https://github.com/xiaosongwang/MIRQI`

**Comment by Xjmengnieer** [comment]
THANKS !!!!
