### ISSUE TITLE
Running mimic？

### ISSUE THREAD

**Issue by SUNQIANG818** [uzh-dqbm-cmi/ARGON#12]
Hi,

Thanks for sharing the code. What are the arguments for running the MIMIC-CXR experiment and does it need a vocab.pickle and new_annotation.json file like iu_xray?

Thanks

**Comment by nooralahzadeh** [comment]
Hi, 
Yes, give me your email address and I will send you!

Best

**Comment by SUNQIANG818** [comment]
Hi,
My email address is sunq1027@gmail.com. Thanks

**Comment by SUNQIANG818** [comment]
Hi,
Could you please send me the vocab.pickle and the  new_annotation.json file of MIMIC-CXR dataset?

Thanks

**Comment by FJYfxt** [comment]
Hi,
Could you please send me the vocab.pickle and the new_annotation.json file of MIMIC-CXR dataset? My email address is fanjunyan218@mail.ncut.edu.cn

Thanks!

**Comment by FJYfxt** [comment]
> Hi, My email address is [sunq1027@gmail.com](mailto:sunq1027@gmail.com). Thanks

Hi,
Could you please send me the vocab.pickle and the new_annotation.json file of MIMIC-CXR dataset? My email address is [fanjunyan218@mail.ncut.edu.cn](mailto:fanjunyan218@mail.ncut.edu.cn)

Thanks!

**Comment by FJYfxt** [comment]
> Hi, Yes, give me your email address and I will send you!
> 
> Best
Hi,
Could you please send me the vocab.pickle and the new_annotation.json file of MIMIC-CXR dataset? My email address is [fanjunyan218@mail.ncut.edu.cn](mailto:fanjunyan218@mail.ncut.edu.cn)

Thanks!

**Comment by nooralahzadeh** [comment]
Hi, You can find these data in the following shared folder:
https://drive.google.com/drive/folders/1fYMoChvQGkGlZDlD-w04lk7-u6AJNkkJ?usp=share_link
