### ISSUE TITLE
CE metrics

### ISSUE THREAD

**Issue by anicolson** [uzh-dqbm-cmi/ARGON#2]
Hi, would you be able to share specifically how you computed the Clinical Efficacy (CE) precision, recall, and F1 score metrics? 

I see that you referenced https://github.com/MIT-LCP/mimic-cxr/tree/master/txt in your paper, are you using the code from: https://github.com/MIT-LCP/mimic-cxr/blob/master/txt/validation/compare_negbio_and_chexpert.ipynb specifically? 

Thanks.

**Comment by nooralahzadeh** [comment]
Hi, Sorry to later answer,
Yes, we used the coder from `https://github.com/MIT-LCP/mimic-cxr/blob/master/txt/validation/compare_negbio_and_chexpert.ipynb` to calculate the CE's related metrics.
