### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Jcek** [uzh-dqbm-cmi/ARGON#3]
Dear authors:
       Thanks for providing the code for the paper,could you please provide the dataset link of iu-xray? thanks!

**Comment by Jcek** [comment]
providing the vocab.pickle is also OK

**Comment by nooralahzadeh** [comment]
Hi, Thanks for reaching out, You can find the iu-xray dataset in the following link, which is also mentioned in the paper : 
Datasets section of `https://github.com/cuhksz-nlp/R2Gen`
`https://drive.google.com/file/d/1c0BXEuDy8Cmm2jfN0YYGkQxFZd2ZIoLg/view`
