### ISSUE TITLE
The construction of the high-level context

### ISSUE THREAD

**Issue by Markin-Wang** [uzh-dqbm-cmi/ARGON#4]
Hi, thanks for your work and sharing the code.
Can you provide the script to construct the high-level context?
I can see that in the dataloader, there should be a 'input_bart' attribute in the json file which I cannot found in the files downloaded from R2Gen json file.

Best Regards,
Jun

**Comment by nooralahzadeh** [comment]
Hi, thanks for the issue.
I uploaded the JSON file related to the high-level context.
