### ISSUE TITLE
dataset new_annotation.json  vocab.pickle

### ISSUE THREAD

**Issue by mylu2021** [uzh-dqbm-cmi/ARGON#5]
Dear Author,
Thanks for your great work. It helps me a lot, but the problem without vocab.pickle and new_annotation.json troubles me for a long time. I wonder could u help me with that, please..

**Comment by nooralahzadeh** [comment]
Hi,
Thanks for your interest in our work. Please let me know your email. I will send you the files.

**Comment by mylu2021** [comment]
Thanks very much! Here are my email 2824175421@qq.com.

**Comment by nooralahzadeh** [comment]
Sent!

**Comment by noonisy** [comment]
> Sent!

Hello, thanks for sharing your code!
I have the same problem, Can you seed me vocab.pickle and new_annotaion.json, too?
My email is noonisy5@gmail.com.
Looking forward to your reply, thanks again.

**Comment by wyh196646** [comment]
@nooralahzadeh Dear Author,I have same problem,Could you please send me? I wonder could u help me,my email is 1966463192@qq.com

**Comment by nooralahzadeh** [comment]
I upload the data to GitHub.
Thanks
