### ISSUE TITLE
Running MIMIC-CXR?

### ISSUE THREAD

**Issue by 2533245542** [uzh-dqbm-cmi/ARGON#7]
Hi,

Thanks for sharing the code. What are the arguments for running the MIMIC-CXR experiment and does it need a vocab.pickle and new_annotation.json file like iu_xray?

Thanks

**Comment by nooralahzadeh** [comment]
I put in the following links:
https://drive.google.com/drive/folders/1fYMoChvQGkGlZDlD-w04lk7-u6AJNkkJ?usp=share_link
